version: "3.9"
services:
  vision-web:
    build: vision
    environment:
      - NUM_DETECTIONS=5
      - DETECTION_TOLERANCE=25
      - DEBUG=1
    ports:
      - "8003:8003"
    volumes:
      - ./vision/.:/app
  redis:
    image: "redis:alpine"
