version: "3.9"
services:
  vision-web:
    build: vision
    environment:
      - NUM_DETECTIONS=5
      - DETECTION_TOLERANCE=25
      - DEBUG=1
      - DILATION_ITERATIONS=2
      - DILATION_KERNAL_SIZE=5
      - ALPHANUMERIC_MODEL_THRESHOLD=0.7
    ports:
      - "8003:8003"
  redis:
    image: "redis:alpine"
