version: "3.9"
services:
  vision-web:
    build: vision
    environment:
      - DEBUG=1
      - DETECTION_TOLERANCE=15
      - DILATION_ITERATIONS=2
      - DILATION_KERNAL_SIZE=5
      - MIN_DILATION_SIZE=80
      - POLAR_SHAPE_GRANULARITY=100
      - CONCAVE_SHAPE_AREA_RATIO_THRESHOLD=0.83
      - ALPHANUMERIC_DETECTION_PADDING=5
      - ALPHANUMERIC_MODEL_THRESHOLD=0.7
      - EMERGENT_MODEL_THRESHOLD=0.85
      - CAMERA_SENSOR_WIDTH=2.0
      - CAMERA_FOCAL_LENGTH=1.0
    ports:
      - "8003:8003"
    volumes:
     - ./vision/:/app/
  redis:
    image: "redis:alpine"
